### ISSUE TITLE
Presentación de HIP sobre manejo de cuentas

### ISSUE THREAD

**Issue by herniadlf** [OpenProofOfHumanity/PoH-CDC#10]
Hacer una presentación resumida de lo que busca la hip sobre manejo de cuentas (https://gov.proofofhumanity.id/t/phase-1-hip-xx-explicit-account-management/2328/8) y recibir feedback al respecto.

**Comment by luiandresgonzalez** [comment]
Cerrado por inactividad. Puede reabrirse en cualquier momento!
