### ISSUE TITLE
Mi primer trabajo en crypto/web3

### ISSUE THREAD

**Issue by nicocryptonico** [OpenProofOfHumanity/PoH-CDC#5]
Me gustaría contar este miércoles que conseguí trabajo y que la oportunidad llegó por estar presente en las charlas de la comunidad de PoH en español.

Contar en qué proyecto estoy colaborando.
Comentar sobre una nueva vacante para quién quiera postularse.

**Comment by OpenProofOfHumanity** [comment]
Nico, cual es tu user en telegram?

**Comment by nicocryptonico** [comment]
https://t.me/n_ubi

**Comment by luiandresgonzalez** [comment]
Charlado en CDC 28
