### ISSUE TITLE
Iniciativas anexas a PoH

### ISSUE THREAD

**Issue by Dacastillo** [OpenProofOfHumanity/PoH-CDC#6]
Al hablar del Grant de Gitcoin, se habló de iniciativas diversas que usarían PoH.  Estaría bueno contar qué están armando. Sobre todo Cohere and Solidarity Card,de las que hay poca información disponible.

**Comment by luiandresgonzalez** [comment]
Se puede hablar, yo no tengo info, si vos tenés algo porfa mandame por DM así exponemos esos updates.

**Comment by Dacastillo** [comment]
Me parece genial. Yo tampoco tengo mucha información. Sería ideal buscar gente que la tenga para la próxima charla. ¿Quienes están en esos proyectos?

**Comment by luiandresgonzalez** [comment]
Si lo propones, vas a tener que buscarlos! 🙂

**Comment by luiandresgonzalez** [comment]
Cerrado por inactividad. Puede reabrirse en cualquier momento!
