### ISSUE TITLE
Definir propósito

### ISSUE THREAD

**Issue by changuitoeth** [OpenProofOfHumanity/PoH-CDC#7]
Propongo conversar y re-definir el propósito de PoH. 
La actividad consta de 4 etapas. 
Etapa 1: Pensar cuales son los insights que tenemos, a nivel abierto, discutir que es lo que se quiere lograr, con que contamos, como nos imaginamos el mundo con PoH. Estas ideas se colocan en comunidad en postit. En el primer cuadro. 
Etapa 2: Redactar el propósito con comunidad.
Etapa 3: Armar un post en gov para discutirlo. 
Etapa 4: Votarlo en snapshot. 
[Link al documento. ](https://miro.com/app/board/o9J_lz5aDak=/?moveToWidget=3458764528299628252&cot=14)
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/19919532/175958821-22e97270-5ccb-460b-aa55-86af9e43b493.png">

**Comment by luiandresgonzalez** [comment]
Cerrado por inactividad. Puede reabrirse en cualquier momento!
