### ISSUE TITLE
¿Es el $UBI económicamente sostenible?

### ISSUE THREAD

**Issue by sepu85** [OpenProofOfHumanity/PoH-CDC#9]
Una emisión de tokens que aumenta progresivamente a según de la cantidad de usuarios registrados en PoH y el tiempo que parece destinar el precio del $UBI a 0 en el largo plazo. Los Vaults de democracy.earth parecen una buena solución, pero sería efectiva sólo si logra quemar $UBIs a una tasa en los mismos rangos en que el $UBI se emite.

¿Que tan verdad o mito es la afirmación de que cada $UBI está respaldado por una hora humana?¿existen pólizas de emisión alternativas que proyecten, por diseño cryptoeconómico, una subida del precio del $UBI mientras que aumenta su adopción?

En mi experiencia con otros proyectos crypto-UBI puedo afirmar que sí es posible un diseño de póliza monetaria que incluya los debidos incentivos para sostener y crecer la economía en torno al token $UBI y quisiera proponer un debate abierto al respecto.

**Comment by SoBoL84** [comment]
Muy interesante gustavo!

**Comment by luiandresgonzalez** [comment]
Cerrado por inactividad. Puede reabrirse en cualquier momento!
